# Generated by Django 3.1 on 2020-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, default='https://www.flaticon.com/svg/static/icons/svg/2598/2598023.svg'),
        ),
    ]
